# Usando uma imagem base do Nixpacks
FROM ghcr.io/railwayapp/nixpacks:ubuntu-1725321821

# Define o diretório de trabalho
WORKDIR /app/

# Copia os arquivos necessários
COPY . .

# Instala as dependências sem as devDependencies
RUN --mount=type=cache,id=s/4dedc5ea-cde5-4ae9-9a29-85e609f15371-/root/npm,target=/root/.npm npm ci --omit=dev

# Define o comando para iniciar a aplicação
CMD ["npm", "start"]
